// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadScheduler returns the embedded CollectionSpec for scheduler.
func loadScheduler() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SchedulerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load scheduler: %w", err)
	}

	return spec, err
}

// loadSchedulerObjects loads scheduler and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*schedulerObjects
//	*schedulerPrograms
//	*schedulerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSchedulerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadScheduler()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// schedulerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type schedulerSpecs struct {
	schedulerProgramSpecs
	schedulerMapSpecs
	schedulerVariableSpecs
}

// schedulerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type schedulerProgramSpecs struct {
	HandleSchedSwitch    *ebpf.ProgramSpec `ebpf:"handle_sched_switch"`
	HandleSchedWakeup    *ebpf.ProgramSpec `ebpf:"handle_sched_wakeup"`
	HandleSchedWakeupNew *ebpf.ProgramSpec `ebpf:"handle_sched_wakeup_new"`
}

// schedulerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type schedulerMapSpecs struct {
	Config     *ebpf.MapSpec `ebpf:"config"`
	Events     *ebpf.MapSpec `ebpf:"events"`
	LostEvents *ebpf.MapSpec `ebpf:"lost_events"`
}

// schedulerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type schedulerVariableSpecs struct {
}

// schedulerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSchedulerObjects or ebpf.CollectionSpec.LoadAndAssign.
type schedulerObjects struct {
	schedulerPrograms
	schedulerMaps
	schedulerVariables
}

func (o *schedulerObjects) Close() error {
	return _SchedulerClose(
		&o.schedulerPrograms,
		&o.schedulerMaps,
	)
}

// schedulerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSchedulerObjects or ebpf.CollectionSpec.LoadAndAssign.
type schedulerMaps struct {
	Config     *ebpf.Map `ebpf:"config"`
	Events     *ebpf.Map `ebpf:"events"`
	LostEvents *ebpf.Map `ebpf:"lost_events"`
}

func (m *schedulerMaps) Close() error {
	return _SchedulerClose(
		m.Config,
		m.Events,
		m.LostEvents,
	)
}

// schedulerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSchedulerObjects or ebpf.CollectionSpec.LoadAndAssign.
type schedulerVariables struct {
}

// schedulerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSchedulerObjects or ebpf.CollectionSpec.LoadAndAssign.
type schedulerPrograms struct {
	HandleSchedSwitch    *ebpf.Program `ebpf:"handle_sched_switch"`
	HandleSchedWakeup    *ebpf.Program `ebpf:"handle_sched_wakeup"`
	HandleSchedWakeupNew *ebpf.Program `ebpf:"handle_sched_wakeup_new"`
}

func (p *schedulerPrograms) Close() error {
	return _SchedulerClose(
		p.HandleSchedSwitch,
		p.HandleSchedWakeup,
		p.HandleSchedWakeupNew,
	)
}

func _SchedulerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed scheduler_bpfeb.o
var _SchedulerBytes []byte
